# 🧹 Data Cleaning

## Objective
- Data cleaning is the process of identifying and correcting issues in a dataset, such as duplicate records, missing values, unnecessary columns, incorrect data types, unwanted spaces, and inconsistent data formats.
- We clean data to ensure that our analysis is accurate, reliable, and capable of solving business problems effectively without introducing errors or bias.
- Data cleaning is an important step because poor-quality data can lead to incorrect analysis, misleading insights, and poor business decisions.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r"D:\GitHub Repositories\Uber-Ride-Sharing-Analytics\datasets\uber.csv")
df.shape

(200000, 9)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 9 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Unnamed: 0         200000 non-null  int64
 1   key                200000 non-null  object
 2   fare_amount        200000 non-null  float64
 3   pickup_datetime    200000 non-null  object
 4   pickup_longitude   200000 non-null  float64
 5   pickup_latitude    200000 non-null  float64
 6   dropoff_longitude  199999 non-null  float64
 7   dropoff_latitude   199999 non-null  float64
 8   passenger_count    200000 non-null  int64
dtypes: float64(5), int64(2), object(2)
memory usage: 13.7+ MB

In [5]:
df.head()

,Unnamed: 0,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,24238194,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06 UTC,-73.999817,40.738354,-73.999512,40.723217,1
1,27835199,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56 UTC,-73.994355,40.728225,-73.994710,40.750325,1
2,44984355,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00 UTC,-74.005043,40.740770,-73.962565,40.772647,1
3,25894730,2009-06-26 08:22:21.0000001,5.3,2009-06-26 08:22:21 UTC,-73.976124,40.790844,-73.965316,40.803349,3
4,17610152,2014-08-28 17:47:00.000000188,16.0,2014-08-28 17:47:00 UTC,-73.925023,40.744085,-73.973082,40.761247,5

In [6]:
df = df.drop(columns=['Unnamed: 0'])

In [7]:
df.columns

Index(['key', 'fare_amount', 'pickup_datetime', 'pickup_longitude',
       'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude',
       'passenger_count'],
      dtype='object')

### Step 1: Removed Unnecessary Column

**Column:** `Unnamed: 0`

**Reason:**
The `Unnamed: 0` column did not provide any business or analytical value. It appeared to be an unnecessary index column and was removed to keep the dataset clean and focused on relevant features.

In [8]:
has_duplicates = df.duplicated().any()
print(has_duplicates)

False

In [9]:
duplicate_count = df.duplicated().sum()
print(f"There are {duplicate_count} duplicate rows.")

There are 0 duplicate rows.

### Step 2: Checked Duplicate Records

**Result:**
No duplicate rows were found in the dataset.

**Reason:**
Duplicate records can lead to incorrect business insights, such as inflated trip counts and revenue. Since no duplicate rows were detected, no cleaning action was required.

In [10]:
df_missing_rows = df[df.isna().any(axis=1)]
print(df_missing_rows)

                               key  fare_amount          pickup_datetime  \
87946  2013-07-02 03:51:57.0000001         24.1  2013-07-02 03:51:57 UTC

       pickup_longitude  pickup_latitude  dropoff_longitude  dropoff_latitude  \
87946        -73.950581        40.779692                NaN               NaN

       passenger_count
87946                0

In [11]:
df.iloc[87946]

key                  2013-07-02 03:51:57.0000001
fare_amount                                 24.1
pickup_datetime          2013-07-02 03:51:57 UTC
pickup_longitude                      -73.950581
pickup_latitude                        40.779692
dropoff_longitude                            NaN
dropoff_latitude                             NaN
passenger_count                                0
Name: 87946, dtype: object

In [12]:
df = df.dropna()

In [13]:
df.shape

(199999, 8)

In [14]:
df.isna().sum()

key                  0
fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    0
dropoff_latitude     0
passenger_count      0
dtype: int64

### Step 3: Handled Missing Values

**Finding:**
One row contained missing values in the `dropoff_longitude` and `dropoff_latitude` columns.

**Decision:**
The affected row was removed from the dataset.

**Reason:**
Since only one row out of 200,000 contained missing geographic coordinates, removing it had a negligible impact on the dataset while preserving data quality. Filling these values could have introduced inaccurate location data and biased the analysis.

In [15]:
df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'])

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 199999 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   key                199999 non-null  object
 1   fare_amount        199999 non-null  float64
 2   pickup_datetime    199999 non-null  datetime64[ns, UTC]
 3   pickup_longitude   199999 non-null  float64
 4   pickup_latitude    199999 non-null  float64
 5   dropoff_longitude  199999 non-null  float64
 6   dropoff_latitude   199999 non-null  float64
 7   passenger_count    199999 non-null  int64
dtypes: datetime64[ns, UTC](1), float64(5), int64(1), object(1)
memory usage: 13.7+ MB

### Step 4: Fixed Incorrect Data Type

**Column:** `pickup_datetime`

**Issue:**
The `pickup_datetime` column was stored as an object (string) instead of a datetime data type.

**Action Taken:**
Converted the column to the datetime data type using `pd.to_datetime()`.

**Reason:**
Converting the column to datetime enables date and time-based analysis, such as extracting hours, weekdays, months, and identifying peak demand periods.

In [17]:
df['fare_amount'].describe()

count    199999.000000
mean         11.359892
std           9.901760
min         -52.000000
25%           6.000000
50%           8.500000
75%          12.500000
max         499.000000
Name: fare_amount, dtype: float64

In [18]:
zero_count = (df['fare_amount'] == 0).sum()
zero_count

np.int64(5)

In [21]:
df = df[df['fare_amount'] >= 0]

In [22]:
df['fare_amount'].min()

np.float64(0.0)

### Step 5: Handled Invalid Fare Values

**Finding:**
The `fare_amount` column contained negative values, which are not valid for completed Uber rides.

**Decision:**
Removed rows where `fare_amount` was less than 0.

**Reason:**
Negative fares are not possible in normal business operations and would distort revenue and fare analysis. Fare values equal to 0 were retained because, without cancellation or payment status information, they could represent valid business scenarios such as promotions or refunds.

In [24]:
df['passenger_count'].describe()

count    199982.000000
mean          1.684502
std           1.385977
min           0.000000
25%           1.000000
50%           1.000000
75%           2.000000
max         208.000000
Name: passenger_count, dtype: float64

In [25]:
zero_count = (df['passenger_count'] == 0).sum()
zero_count

np.int64(708)

In [28]:
six_count = (df['passenger_count'] > 6).sum()
six_count

np.int64(1)

In [29]:
df = df[df['passenger_count'] <= 6]

In [30]:
df['passenger_count'].max()

np.int64(6)

### Step 6: Handled Invalid Passenger Counts

**Finding:**
The `passenger_count` column contained one unrealistic value greater than 6.

**Decision:**
Removed rows where `passenger_count` was greater than 6.

**Reason:**
An Uber vehicle cannot realistically carry more than 6 passengers. Passenger counts equal to 0 were retained because the dataset lacked ride status or cancellation information, making it impossible to determine whether those records were invalid.

In [35]:
df['pickup_longitude'].describe()

count    199981.000000
mean        -72.527501
std          11.438322
min       -1340.648410
25%         -73.992065
50%         -73.981823
75%         -73.967155
max          57.418457
Name: pickup_longitude, dtype: float64

In [36]:
df['pickup_latitude'].describe()

count    199981.000000
mean         39.935808
std           7.720902
min         -74.015515
25%          40.734795
50%          40.752592
75%          40.767158
max        1644.421482
Name: pickup_latitude, dtype: float64

In [37]:
df['dropoff_longitude'].describe()

count    199981.000000
mean        -72.525531
std          13.116989
min       -3356.666300
25%         -73.991407
50%         -73.980092
75%         -73.963658
max        1153.572603
Name: dropoff_longitude, dtype: float64

In [38]:
df['dropoff_latitude'].describe()

count    199981.000000
mean         39.924020
std           6.794544
min        -881.985513
25%          40.733824
50%          40.753042
75%          40.768002
max         872.697628
Name: dropoff_latitude, dtype: float64

In [44]:
pick_lat = (df['pickup_latitude'] < -90).sum()
pick_lat

np.int64(0)

In [58]:
pick_lat = (df['pickup_latitude'] > 90).sum()
pick_lat

np.int64(4)

In [46]:
pick_long = (df['pickup_longitude'] < -180).sum()
pick_long

np.int64(7)

In [47]:
pick_long = (df['pickup_longitude'] > 180).sum()
pick_long

np.int64(0)

In [48]:
drop_lat = (df['dropoff_latitude'] < -90).sum()
drop_lat

np.int64(1)

In [49]:
drop_lat = (df['dropoff_latitude'] > 90).sum()
drop_lat

np.int64(2)

In [50]:
drop_long = (df['dropoff_longitude'] < -180).sum()
drop_long

np.int64(2)

In [51]:
drop_long = (df['dropoff_longitude'] > 180).sum()
drop_long

np.int64(1)

In [60]:
invalid_coordinate_count = ((df['pickup_latitude'] < -90) |
           (df['pickup_latitude'] > 90) |
           (df['pickup_longitude'] < -180) |
           (df['pickup_longitude'] > 180) |
           (df['dropoff_latitude'] < -90) |
           (df['dropoff_latitude'] > 90) |
           (df['dropoff_longitude'] < -180) |
           (df['dropoff_longitude'] > 180)).sum()
invalid_coordinate_count

np.int64(12)

In [61]:
df = df[(df['pickup_latitude'] >= -90) &
           (df['pickup_latitude'] <= 90) &
           (df['pickup_longitude'] >= -180) &
           (df['pickup_longitude'] <= 180) &
           (df['dropoff_latitude'] >= -90) &
           (df['dropoff_latitude'] <= 90) &
           (df['dropoff_longitude'] >= -180) &
           (df['dropoff_longitude'] <= 180)]

In [63]:
df['pickup_latitude'].min()

np.float64(-74.01551500000001)

In [64]:
df['pickup_latitude'].max()

np.float64(48.01876)

In [65]:
df['pickup_longitude'].min()

np.float64(-93.824668)

In [66]:
df['pickup_longitude'].max()

np.float64(40.808425)

In [67]:
df['dropoff_latitude'].min()

np.float64(-74.01575)

In [68]:
df['dropoff_latitude'].max()

np.float64(45.031598)

In [69]:
df['dropoff_longitude'].min()

np.float64(-75.458978633981)

In [70]:
df['dropoff_longitude'].max()

np.float64(40.831932)

### Step 7: Handled Invalid Coordinates

**Finding:**
The dataset contained rows with latitude and longitude values outside the valid geographic ranges.

**Decision:**
Removed rows containing invalid coordinates.

**Reason:**
Latitude values must be between -90 and 90, and longitude values must be between -180 and 180. Invalid coordinates would lead to inaccurate geographic analysis and visualizations.

In [71]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 199969 entries, 0 to 199999
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   key                199969 non-null  object
 1   fare_amount        199969 non-null  float64
 2   pickup_datetime    199969 non-null  datetime64[ns, UTC]
 3   pickup_longitude   199969 non-null  float64
 4   pickup_latitude    199969 non-null  float64
 5   dropoff_longitude  199969 non-null  float64
 6   dropoff_latitude   199969 non-null  float64
 7   passenger_count    199969 non-null  int64
dtypes: datetime64[ns, UTC](1), float64(5), int64(1), object(1)
memory usage: 13.7+ MB

In [72]:
df.describe()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
count,199969.000000,199969.000000,199969.000000,199969.000000,199969.000000,199969.000000
mean,11.362258,-72.501654,39.917862,-72.511845,39.922160,1.683471
std,9.897235,10.450416,6.130682,10.411390,6.117288,1.306938
min,0.000000,-93.824668,-74.015515,-75.458979,-74.015750,0.000000
25%,6.000000,-73.992065,40.734792,-73.991407,40.733824,1.000000
50%,8.500000,-73.981822,40.752591,-73.980092,40.753042,1.000000
75%,12.500000,-73.967155,40.767157,-73.963658,40.768001,2.000000
max,499.000000,40.808425,48.018760,40.831932,45.031598,6.000000

In [73]:
df.shape

(199969, 8)

In [74]:
df.columns

Index(['key', 'fare_amount', 'pickup_datetime', 'pickup_longitude',
       'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude',
       'passenger_count'],
      dtype='object')

## Step 8: Final Dataset Validation

**Validation Checks Performed:**

- Verified data types using `df.info()`
- Confirmed no missing values remained
- Reviewed summary statistics using `df.describe()`
- Verified the final dataset shape
- Confirmed the expected columns were present

**Result:**

The dataset is clean, consistent, and ready for feature engineering, exploratory data analysis (EDA), SQL analysis, and dashboard development.

In [75]:
df.to_csv(r"D:\GitHub Repositories\Uber-Ride-Sharing-Analytics\datasets\cleaned_uber.csv", index=False)

In [76]:
cleaned_df = pd.read_csv(r"D:\GitHub Repositories\Uber-Ride-Sharing-Analytics\datasets\cleaned_uber.csv")

In [77]:
cleaned_df.head()

,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06+00:00,-73.999817,40.738354,-73.999512,40.723217,1
1,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56+00:00,-73.994355,40.728225,-73.994710,40.750325,1
2,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00+00:00,-74.005043,40.740770,-73.962565,40.772647,1
3,2009-06-26 08:22:21.0000001,5.3,2009-06-26 08:22:21+00:00,-73.976124,40.790844,-73.965316,40.803349,3
4,2014-08-28 17:47:00.000000188,16.0,2014-08-28 17:47:00+00:00,-73.925023,40.744085,-73.973082,40.761247,5