# Feature Engineering

## Objective
Feature Engineering is the process of creating new columns (features) from existing data to make analysis easier and more meaningful.

It helps answer business questions, understand customer behavior, and generate valuable insights for stakeholders.

In [29]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv(r"D:\GitHub Repositories\Uber-Ride-Sharing-Analytics\datasets\cleaned_uber.csv")
df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199969 entries, 0 to 199968
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   key                199969 non-null  object
 1   fare_amount        199969 non-null  float64
 2   pickup_datetime    199969 non-null  datetime64[ns, UTC]
 3   pickup_longitude   199969 non-null  float64
 4   pickup_latitude    199969 non-null  float64
 5   dropoff_longitude  199969 non-null  float64
 6   dropoff_latitude   199969 non-null  float64
 7   passenger_count    199969 non-null  int64
dtypes: datetime64[ns, UTC](1), float64(5), int64(1), object(1)
memory usage: 12.2+ MB

In [17]:
df['pickup_hour'] = df['pickup_datetime'].dt.hour
df[['pickup_datetime', 'pickup_hour']].head()

            pickup_datetime  pickup_hour
0 2015-05-07 19:52:06+00:00           19
1 2009-07-17 20:04:56+00:00           20
2 2009-08-24 21:45:00+00:00           21
3 2009-06-26 08:22:21+00:00            8
4 2014-08-28 17:47:00+00:00           17

### Step 1: Extract Pickup Hour

**Finding:**
The `pickup_datetime` column contains both date and time information.

**Feature Created:**
`pickup_hour`

**Reason:**
Extracting the pickup hour makes it easier to analyze hourly demand, identify peak hours, and answer business questions such as "At what hour do customers book the most Uber rides?"

In [16]:
df['pickup_day'] = df['pickup_datetime'].dt.day
df[['pickup_datetime', 'pickup_day']].head()

            pickup_datetime  pickup_day
0 2015-05-07 19:52:06+00:00           7
1 2009-07-17 20:04:56+00:00          17
2 2009-08-24 21:45:00+00:00          24
3 2009-06-26 08:22:21+00:00          26
4 2014-08-28 17:47:00+00:00          28

### Step 2: Extract Pickup Day

**Feature Created:**
`pickup_day`

**Reason:**
The pickup day helps analyze ride patterns across different days of the month and supports time-based business analysis.

In [15]:
df['pickup_month'] = df['pickup_datetime'].dt.month
df[['pickup_datetime', 'pickup_month']].head()

            pickup_datetime  pickup_month
0 2015-05-07 19:52:06+00:00             5
1 2009-07-17 20:04:56+00:00             7
2 2009-08-24 21:45:00+00:00             8
3 2009-06-26 08:22:21+00:00             6
4 2014-08-28 17:47:00+00:00             8

### Step 3: Extract Pickup Month

**Feature Created:**
`pickup_month`

**Reason:**
The pickup month helps analyze monthly ride demand, identify seasonal trends, and compare business performance across different months.

In [18]:
df['pickup_year'] = df['pickup_datetime'].dt.year
df[['pickup_datetime', 'pickup_year']].head()

            pickup_datetime  pickup_year
0 2015-05-07 19:52:06+00:00         2015
1 2009-07-17 20:04:56+00:00         2009
2 2009-08-24 21:45:00+00:00         2009
3 2009-06-26 08:22:21+00:00         2009
4 2014-08-28 17:47:00+00:00         2014

### Step 4: Extract Pickup Year

**Feature Created:**
`pickup_year`

**Reason:**
The pickup year helps analyze yearly ride trends, compare business performance across years, and identify long-term growth patterns.

In [27]:
df['pickup_day_name'] = df['pickup_datetime'].dt.day_name()
df[['pickup_datetime', 'pickup_day_name']].head()

            pickup_datetime pickup_day_name
0 2015-05-07 19:52:06+00:00        Thursday
1 2009-07-17 20:04:56+00:00          Friday
2 2009-08-24 21:45:00+00:00          Monday
3 2009-06-26 08:22:21+00:00          Friday
4 2014-08-28 17:47:00+00:00        Thursday

### Step 5: Extract Pickup Day Name

**Feature Created:**
`pickup_day_name`

**Reason:**
The pickup day name helps analyze ride demand by weekday, identify the busiest days, and support weekly business reporting.

In [31]:
df['day_type'] = np.where(
    (df['pickup_day_name'] == 'Saturday') | (df['pickup_day_name'] == 'Sunday'),
    "Weekend",
    "Weekday"
)
df[['pickup_day_name', 'day_type']].head(10)

  pickup_day_name day_type
0        Thursday  Weekday
1          Friday  Weekday
2          Monday  Weekday
3          Friday  Weekday
4        Thursday  Weekday
5        Saturday  Weekend
6          Sunday  Weekend
7         Tuesday  Weekday
8          Friday  Weekday
9        Thursday  Weekday

### Step 6: Create Day Type

**Feature Created:**
`day_type`

**Reason:**
This feature categorizes rides into **Weekday** and **Weekend**, making it easier to compare ride demand and revenue patterns between working days and weekends.

In [33]:
df.head()

,key,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_hour,pickup_day,pickup_month,pickup_year,pickup_day_name,pickup_month_name,day_type
0,2015-05-07 19:52:06.0000003,7.5,2015-05-07 19:52:06+00:00,-73.999817,40.738354,-73.999512,40.723217,1,19,7,5,2015,Thursday,May,Weekday
1,2009-07-17 20:04:56.0000002,7.7,2009-07-17 20:04:56+00:00,-73.994355,40.728225,-73.994710,40.750325,1,20,17,7,2009,Friday,July,Weekday
2,2009-08-24 21:45:00.00000061,12.9,2009-08-24 21:45:00+00:00,-74.005043,40.740770,-73.962565,40.772647,1,21,24,8,2009,Monday,August,Weekday
3,2009-06-26 08:22:21.0000001,5.3,2009-06-26 08:22:21+00:00,-73.976124,40.790844,-73.965316,40.803349,3,8,26,6,2009,Friday,June,Weekday
4,2014-08-28 17:47:00.000000188,16.0,2014-08-28 17:47:00+00:00,-73.925023,40.744085,-73.973082,40.761247,5,17,28,8,2014,Thursday,August,Weekday

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 199969 entries, 0 to 199968
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   key                199969 non-null  object
 1   fare_amount        199969 non-null  float64
 2   pickup_datetime    199969 non-null  datetime64[ns, UTC]
 3   pickup_longitude   199969 non-null  float64
 4   pickup_latitude    199969 non-null  float64
 5   dropoff_longitude  199969 non-null  float64
 6   dropoff_latitude   199969 non-null  float64
 7   passenger_count    199969 non-null  int64
 8   pickup_hour        199969 non-null  int32
 9   pickup_day         199969 non-null  int32
 10  pickup_month       199969 non-null  int32
 11  pickup_year        199969 non-null  int32
 12  pickup_day_name    199969 non-null  object
 13  pickup_month_name  199969 non-null  object
 14  day_type           199969 non-null  object
dtypes: datetime64[ns, UTC](1), float64(5), int32(4), int64(1), object(4)
memory usage: 19.8+ MB

In [35]:
df.columns

Index(['key', 'fare_amount', 'pickup_datetime', 'pickup_longitude',
       'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude',
       'passenger_count', 'pickup_hour', 'pickup_day', 'pickup_month',
       'pickup_year', 'pickup_day_name', 'pickup_month_name', 'day_type'],
      dtype='object')

In [36]:
df.describe()

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_hour,pickup_day,pickup_month,pickup_year
count,199969.000000,199969.000000,199969.000000,199969.000000,199969.000000,199969.000000,199969.000000,199969.000000,199969.000000,199969.000000
mean,11.362258,-72.501654,39.917862,-72.511845,39.922160,1.683471,13.491531,15.704994,6.282009,2011.742395
std,9.897235,10.450416,6.130682,10.411390,6.117288,1.306938,6.515414,8.687527,3.438956,1.856356
min,0.000000,-93.824668,-74.015515,-75.458979,-74.015750,0.000000,0.000000,1.000000,1.000000,2009.000000
25%,6.000000,-73.992065,40.734792,-73.991407,40.733824,1.000000,9.000000,8.000000,3.000000,2010.000000
50%,8.500000,-73.981822,40.752591,-73.980092,40.753042,1.000000,14.000000,16.000000,6.000000,2012.000000
75%,12.500000,-73.967155,40.767157,-73.963658,40.768001,2.000000,19.000000,23.000000,9.000000,2013.000000
max,499.000000,40.808425,48.018760,40.831932,45.031598,6.000000,23.000000,31.000000,12.000000,2015.000000

In [ ]:
df['day_type'].value_counts()

### Step 7: Final Validation

**Validation Performed:**
- Verified the first few rows using `df.head()`.
- Confirmed all columns, data types, and non-null values using `df.info()`.
- Reviewed numerical statistics using `df.describe()`.
- Checked the complete list of columns using `df.columns`.
- Verified the `day_type` feature using `value_counts()`.

**Result:**
The dataset passed all validation checks. All engineered features were created successfully, no missing values were introduced, and the dataset is ready for Exploratory Data Analysis (EDA).

In [38]:
df.to_csv(
    r"D:\GitHub Repositories\Uber-Ride-Sharing-Analytics\datasets\feature_engineered_uber.csv",
    index=False
)